language: rust
osx_image: xcode9.2

git:
  submodules: true
  depth: 5

os:
  - osx

rust:
  - 1.29.2

cache: cargo

before_script:
  - sudo gem install xcpretty

script:
  - xcodebuild clean test -scheme XiEditor | xcpretty -s

after_success:
  - bash <(curl -s https://codecov.io/bash)
