language: rust
osx_image: xcode10.1

git:
  submodules: true
  depth: 5

os:
  - osx

rust:
  - 1.31.0

cache: cargo

before_script:
  - sudo gem install xcpretty

script:
  - xcodebuild test -scheme XiEditor | xcpretty -s && exit ${PIPESTATUS[0]}

after_success:
  - bash <(curl -s https://codecov.io/bash)
