# Site settings
apple_help: true  # Flag for conditional markup, if needed.

# Build settings
markdown: kramdown

# Localization collections for Help topics. Add more languages as needed.
collections:
  English.lproj:
    output: true
  Japanese.lproj:
    output: true
  Dutch.lproj:
    output: true
  French.lproj:
    output: true
  Italian.lproj:
    output: true
  German.lproj:
    output: true
  Spanish.lproj:
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: "help-page"
      order: 0

exclude: ['Makefile', 'jekyll-server.command', 'Info.plist']
